"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const tslib_1 = require("tslib");
const express_1 = (0, tslib_1.__importDefault)(require("express"));
const db_1 = require("./db");
const dotenv_1 = (0, tslib_1.__importDefault)(require("dotenv"));
const auth_1 = require("./Controllers/auth");
const userController_1 = require("./Controllers/userController");
const movieController_1 = require("./Controllers/movieController");
dotenv_1.default.config({ path: '../bin/.env' });
(0, db_1.connectDB)();
const app = (0, express_1.default)();
app.use(express_1.default.json());
app.use(express_1.default.urlencoded({ extended: false }));
const auth = "/api/auth";
const user = "/api/user";
const list = "/api/list";
const movie = "/api/movie";
app.post(`${auth}/register`, auth_1.PostUser);
app.post(`${auth}/login`, auth_1.LoginUser);
app.post(`${user}/`, userController_1.UpdateUser);
app.get(`${user}/find/:id`, userController_1.FindUserById);
app.get(`${user}/`, userController_1.FindAllUser);
app.get(`${user}/stats`, userController_1.UserStats);
app.delete(`${user}/:id`, userController_1.DeleteUser);
app.post(`${movie}/`, movieController_1.postMovie);
app.put(`${movie}/:id`, movieController_1.putMovie);
app.delete(`${movie}/:id`, movieController_1.deleteMovie);
app.get(`${movie}/:id`, movieController_1.findMovieById);
app.get(`${movie}/`, movieController_1.findMovie);
const PORT = process.env.PORT || 600;
app.listen(PORT, () => {
    console.log(`App is running on port %d`, PORT);
});
